// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9udFjtyIh_szgdbZ94a54AValjO59kSw',
    appId: '1:666719170989:web:6da4f42d7987f581d17124',
    messagingSenderId: '666719170989',
    projectId: 'decampus-4096',
    authDomain: 'decampus-4096.firebaseapp.com',
    storageBucket: 'decampus-4096.appspot.com',
    measurementId: 'G-CSZBW3PR0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYdoC4NVgY5JqP1AKsmi4SZL_bXfXE9yM',
    appId: '1:666719170989:android:4532f9efb6db5d6ed17124',
    messagingSenderId: '666719170989',
    projectId: 'decampus-4096',
    storageBucket: 'decampus-4096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmf0xkXZA3z03RYJWihWa2911200XTDY',
    appId: '1:666719170989:ios:b7b4f00faf6642f5d17124',
    messagingSenderId: '666719170989',
    projectId: 'decampus-4096',
    storageBucket: 'decampus-4096.appspot.com',
    iosBundleId: 'com.example.decampus',
  );
}
